version: "3.9"
services:
    bun:
        image: oven/bun
        volumes:
            - .:/home/bun/app
        network_mode: host
        working_dir: /home/bun/app
        command: bun run webfont
